### ISSUE TITLE
Adding Address to Employee

### ISSUE THREAD

**Issue by jruan1580** [jruan1580/Rof-Scheduler#63]
Let's add address to the employee:

Fields to add:

AddressLine1
AddressLine2
City,
State,
ZipCode

Things to modify:

- Table definition
- Repository
- Services (create, update, select by id).
- Models

**Comment by bwruan** [comment]
Grooming Note: 

AddressLine1 - varchar(255)
AddressLine2 - varchar(50)
City - varchar(50)
State - varchar(2)
ZipCode - varchar(10)
